name: learn-github-actions.yml
run-name: ${{ github.actor }} is learning github actions
on:
  push:
    branches:
      - master

# Ensure that only one workflow using same concurrency group is running at a time.
concurrency:
  group: build-deploy
  # Cancel the current workflow and execute the newest one
  cancel-in-progress: true

jobs:
  build-project-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-website
          path: dist/**
          if-no-files-found: error

  push-to-production-job:
    needs: build-project-job
    runs-on: ubuntu-latest
    permissions:
      # Allow workflow to write content
      contents: write

    env:
      HEAD_COMMIT_ACTOR_NAME: ${{ github.event.head_commit.author.name }}
      HEAD_COMMIT_ACTOR_EMAIL: ${{ github.event.head_commit.author.email }}
      HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      PRODUCTION_BRANCH: production

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.PRODUCTION_BRANCH }}

      - uses: actions/download-artifact@v3
        with:
          name: compiled-website

      - run: |
          git config user.name $HEAD_COMMIT_ACTOR_NAME
          git config user.email $HEAD_COMMIT_ACTOR_EMAIL

      - run: git add .

      - run: |
          git commit -m "$HEAD_COMMIT_MESSAGE"
          git push origin $PRODUCTION_BRANCH