name: learn-github-actions.yml
run-name: ${{ github.actor }} is learning github actions
on:
  push:
    branches:
      - master

# Ensure that only one workflow using same concurrency group is running at a time.
concurrency:
  group: build-deploy
  # Cancel the current workflow and execute the newest one
  cancel-in-progress: true

jobs:
  build-deploy-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-website
          path: dist/**
          if-no-files-found: error