name: learn-github-actions.yml
run-name: ${{ github.actor }} is learning github actions
on:
  push:
    branches:
      - master
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: '14'

      - name: step-1
        run: |
              "Running step one of the workflow"
              sleep 2s
              echo "Finished running step one of the workflow"

      - name: step-2
        run: | 
              echo "Running step two of the workflow"
              sleep 2s
              echo "Finished running step two of the workflow"